import { Product, ProductList } from '../_models';

export const PRODLISTS: ProductList[] = [

  {
      id: 1,
      name: 'Jumbo',
      products: [
          {id: 1, name: 'kaas', quantity: 4, inStock: true},
          {id: 2, name: 'melk', quantity: 12, inStock: true}
      ]
  },
  {
      id: 2,
      name: 'Albert-Heijn',
      products: [
          {id: 1, name: 'covfefe',   quantity: 4, inStock: false},
          {id: 2, name: 'melk',   quantity: 12, inStock: false},
          {id: 1080, name: 'yogurt',   quantity: 122, inStock: false},
          {id: 532, name: 'parmazan', quantity: 20, inStock: true},
          {id: 3, name: 'vla',   quantity: 3, inStock: false},
          {id: 4, name: 'kroepoek',   quantity: 4, inStock: false},
          {id: 900, name: 'ananas', quantity: 2, inStock: false}
      ]
  }

];

export const PRODUCTS: string[] = [
// tslint:disable:quotemark
"7-up",
"aa drink",
"aardappel salade",
"aardappelballetjes",
"aardappelen",
"aardappelgratin",
"aardappelkroket",
"aardappelkroketten",
"aardappelpartjes",
"aardappelpuree",
"aardappelschotel",
"aardappelzetmeel",
"aardbeien",
"aardbeien ijs",
"aardbeien kwark",
"aardbeien limonade",
"aardbeien yoghurt",
"aardbeienjam",
"abrikozen",
"achterham",
"actimel",
"activia",
"advocaat",
"afbakbroodjes",
"afwasborstel",
"afwasmiddel",
"afwastabletten",
"agavesiroop",
"ahornsiroop",
"aioli",
"ajax",
"alfalfa",
"allerhande box",
"allesbinder",
"allesreiniger",
"alpro soja drink",
"aluminiumfolie",
"always",
"amandelen",
"amandelmeel",
"amandelmelk",
"amandelschaafsel",
"amandelstaaf",
"ambi pur",
"ammonia",
"amstel",
"ananas",
"ananassap",
"ananasschijven",
"ananasstukjes",
"andijvie",
"andy",
"anijsblokje",
"ansjovis",
"antikal",
"appelazijn",
"appelcompote",
"appelen",
"appelflap",
"appelkoeken",
"appelmoes",
"appels",
"appelsap",
"appelsientje",
"appelstroop",
"appeltaart",
"appie today",
"aquarius",
"ardenner paté",
"ariel",
"aromat",
"artisjokken",
"asperges",
"aspergesaus",
"aspergesoep",
"atjar tjampoer",
"aubergine",
"augurken",
"avocado",
"avocado eetrijp",
"axe",
"azijn",
"babi pangang",
"baby-biscuits",
"babybel",
"babydoekjes",
"babyvoeding",
"bacardi",
"bacon",
"badedas",
"badkamerreiniger",
"badschuim",
"bagel",
"baguette",
"bakboter",
"bakmeel",
"bakpapier",
"bakpoeder",
"balsamico",
"bambix",
"bami",
"bami mix",
"bamigroenten",
"banaan",
"bananen",
"bapao",
"bar le duc",
"barbecuesaus",
"basilicum",
"basterdsuiker",
"bastognekoeken",
"batterijen",
"bavaria",
"bbq aanmaakblokjes",
"bbq salade",
"bbq saus",
"becel",
"bechamelsaus",
"beef shanghai",
"beefburgers",
"beenham",
"belegen kaas",
"beltegoed",
"beschuit",
"bessen",
"bessensap",
"bieflapjes",
"biefstuk",
"bier",
"bieslook",
"billendoekjes",
"biogarde yoghurt",
"biotex",
"biscuits",
"bitter lemon",
"bitterballen",
"bitterkoekjes",
"bitters",
"bladerdeeg",
"bladpeterselie",
"bladspinazie",
"bladspinazie (diepvries)",
"blanke vla",
"blauwaderkaas",
"blauwe bessen",
"blauwe druiven",
"blauwe kaas",
"bleekmiddel",
"bleekselderij",
"bloem",
"bloemen",
"bloemenhoning",
"bloemkool",
"bloemkool & broccoli",
"bloemkool ovenschotel",
"bloemkoolroosjes",
"blue band",
"bobotie",
"bodylotion",
"boekweitmeel",
"boemboe",
"boemboe ajam paniki",
"boemboe rode curry",
"boerenbrie",
"boerenkaas",
"boerenkool",
"bokbier",
"bokkenpootjes",
"bolletjes",
"bolognesesaus",
"bona",
"bonbons",
"bonduelle groente",
"bonen",
"bonenkruid",
"boodschappentas",
"boomstammetjes",
"boontjes",
"borrelhapjes",
"borrelnootjes",
"bosbessen",
"bosbessenjam",
"bospeen",
"bospeentje",
"bospeentjes",
"bosui",
"bosuitjes",
"bosvruchten",
"bosvruchtenjam",
"bosvruchtensiroop",
"boter",
"boterhamworst",
"boterhamzakjes",
"boterkoek",
"botersla",
"bouillabaise",
"bouillonblokjes",
"boursin",
"braadboter",
"braadlappen",
"braadworst",
"braeburn appels",
"bramen",
"bramenjam",
"brie",
"brillendoekjes",
"brinta",
"brioche",
"brise",
"broccoli",
"bronwater",
"brood",
"broodbeleg kaas",
"broodbeleg vlees",
"broodbeleg zoet",
"broodjes",
"broodmix",
"browniesmix",
"bruin bier",
"bruin brood",
"bruine bonen",
"bruine suiker",
"bruistabletten",
"brylcream",
"burrito mix",
"burritos",
"cacaoboter",
"cacaopoeder",
"cake",
"cake mix",
"cakemeel",
"calgon",
"calgonit",
"calve saus",
"cambozola",
"camembert",
"canei",
"capri-sun",
"captain morgan",
"carpaccio",
"cashewnoten",
"casselerrib",
"cassis",
"castello blue",
"cayennepeper",
"celavita",
"cereals",
"cervelaatworst",
"chablis",
"champagne",
"champignons",
"champignonsaus",
"champignonschijfjes",
"champignonsoep",
"chardonnay",
"chaudfontaine",
"cheddar",
"cheeseburger",
"cherry tomaten",
"chicken tonight",
"chili con carne",
"chilibonen",
"chilipepertjes",
"chilipoeder",
"chilisaus",
"chinese kool",
"chinese roerbakmix",
"chipolataworstjes",
"chips",
"chiquita bananen",
"chloor",
"chocolade",
"chocolade koeken",
"chocolade pinda's",
"chocolade rozijnen",
"chocolade snoep",
"chocoladebroodje",
"chocoladecake",
"chocolademelk",
"chocolademousse",
"chocoladepasta",
"chocoladereep",
"chocoladesaus",
"chocoladetaart",
"chocoladevla",
"chocolate chip cookies",
"chocomel",
"chocopasta",
"chorizo",
"ciabatta",
"ciabattina",
"cider",
"cif",
"cillit bang",
"citroen",
"citroengras",
"citroensap",
"coca-cola",
"cocktailprikkers",
"cocktailsaus",
"cocktailworstjes",
"cocosmacroon",
"cognac",
"cola",
"cola light",
"compote",
"conditioner",
"conference peren",
"conimex mix",
"coolbest",
"cordon bleu",
"cornedbeef",
"cornflakes",
"corona",
"courgette",
"couscous",
"crackers",
"cracottes",
"cracottes naturel",
"cranberries",
"cranberrysap",
"creme brulee",
"creme fraiche",
"cremespoeling",
"crodino",
"croissants",
"croma",
"croutons",
"cruesli",
"cup a soup",
"curry",
"curry boemboe",
"custard",
"dadels",
"danish blue",
"danoontje",
"davitamon",
"deeg",
"deodorant",
"dessert",
"diarreeremmer",
"diepvriesgroente",
"diepvriesmaaltijd",
"diepvriestas",
"diepvrieszakken",
"digestive koekjes",
"dijonmosterd",
"diksap",
"dille",
"dipsaus",
"dommelsch",
"doperwten",
"doperwten/wortelen",
"doppinda's",
"douchegel",
"doucheschuim",
"douwe egberts",
"dove",
"dragon",
"dreft afwasmiddel",
"dreft wasmiddel",
"dressing",
"driehoek zeep",
"drinkbouillon",
"drinkontbijt",
"drinkyoghurt",
"droge sherry",
"droogshampoo",
"droogtrommeldoekjes",
"drop",
"druiven",
"druivensap",
"druivensuiker",
"druk sluitzakken",
"drumsticks",
"dubbeldrank",
"dubbelfrisss",
"dubbelvla",
"duo penotti",
"duvel",
"earl grey thee",
"edet",
"eieren",
"eierkoeken",
"eiersalade",
"eikenbladsla",
"elitehaver",
"elleboogjesmacaroni",
"elmex",
"emmentaler",
"emping",
"energydrink",
"engelse dropjes",
"entrecote",
"erwtensoep",
"erwtensoeppakket",
"espressokoffie",
"etos",
"evergreen",
"extra belegen kaas",
"facewash",
"fajita mix",
"falafel",
"fanta",
"farfalle",
"feeststol",
"feta",
"fijnwasmiddel",
"filet americain",
"filetlapje",
"filobladerdeeg",
"filodeeg",
"filterkoffie",
"fisherman's friend",
"fleuril",
"focaccia",
"foelie",
"forel",
"frambozen",
"frambozenjam",
"frankfurters",
"fricandeau",
"friet",
"frikandellen",
"fris",
"frisdrank",
"fristi",
"frites",
"fritessaus",
"frituurolie",
"frituursnacks",
"frituurvet",
"fructis",
"fruit",
"fruitbiscuits",
"fruitbox",
"fruitcocktail",
"fruitontbijt",
"fruitrepen",
"fruitsalade",
"fruitsap",
"fruitstroop",
"fudge",
"fusilli",
"galia meloen",
"gamba's",
"garnalen",
"garnalensalade",
"gebak",
"gebakken uitjes",
"gebraden gehakt",
"gecondenseerde melk",
"gedroogd fruit",
"gedroogde abrikozen",
"gedroogde tomaten",
"gegrilde paprika's",
"gehakt",
"gehakt half-om-half",
"gehaktbal",
"gehaktballetjes",
"gehaktkruiden",
"geitenkaas",
"geitenkaas belegen",
"geitenkaas honing",
"geitenkaas oud",
"geitenmelk",
"gel",
"gelatine",
"gelderse gekookte worst",
"gele paprika",
"gele rijst",
"geleisuiker",
"gember",
"gemberkoek",
"gemberpoeder",
"gemberpoeder (djahe)",
"gembersiroop",
"gepelde tomaten",
"geraspte kaas",
"geraspte kokos",
"gerookte kipfilet",
"gerookte zalm",
"gevulde koeken",
"gezeefde tomaten",
"gezichtsreinigingsdoekjes",
"gilette scheerschuim",
"gin",
"ginger ale",
"gist",
"glansspoelmiddel",
"glasreiniger",
"glassex",
"glorix",
"glutenvrije pasta",
"gnocchi",
"goed bezig",
"goede morgen",
"gorgonzola",
"goudreinetten",
"goudsalami",
"goudse kaas",
"goulash",
"gourmet",
"grana padano kaas",
"granaatappelpitjes",
"granenbiscuits",
"granny smith appels",
"grapefruit",
"grapefruitsap",
"griekse yoghurt",
"griesmeelpap",
"griesmeelpudding",
"grillburger",
"grillworst",
"groene asperges",
"groene olijven",
"groene paprika",
"groene peper",
"groene pesto",
"groene thee",
"groente",
"groentebouillontablet",
"groenteburger",
"groentemix",
"groentesaus",
"groentesoep",
"groentesoeppakket",
"grolsch",
"gruyere",
"guacamole",
"gyrosreepjes",
"haarlak",
"haaskarbonade",
"hachee",
"hacheekruiden",
"hacheevlees",
"hagelslag",
"halfvolle melk",
"halvajam",
"halvanaise",
"halvarine",
"ham",
"hamblokjes",
"hamburgerbroodjes",
"hamburgers",
"hamlappen",
"hamreepjes",
"handcreme",
"handperen",
"handschoenen",
"handsinaasappelen",
"handzeep",
"haricots verts",
"haring",
"havermout",
"havermoutpap",
"haverzemelen",
"hazelnootpasta",
"hazelnoten",
"heineken",
"heinz saus",
"heinz tomatenketchup",
"heksenkaas",
"hertog ijs",
"hertog jan",
"hollandaise saus",
"hollandse garnalen",
"hondenkoekjes",
"hondenvoer",
"honig",
"honing",
"hot dogs",
"houmous",
"huggies",
"huishouddoekjes",
"huishoudfolie",
"huisvuilzakken",
"huiswijn",
"hutspot",
"huttenkase",
"huzaren salade",
"huzarensalade",
"hygienische doekjes",
"hüttenkäse",
"ibuprofen",
"ice tea",
"iglo",
"ijs",
"ijsbergsla",
"ijsblokzakjes",
"ijshoorntjes",
"ijsjes",
"ijskoffie",
"ijslollies",
"ijsthee",
"inktvisringen",
"inlegkruisjes",
"instant soepen",
"italiaanse bol",
"italiaanse groentemix",
"italiaanse kruiden",
"jachtsaus",
"jagerburger",
"jalapenos",
"jam",
"japanse mix",
"jenever",
"jeneverbessen",
"jif",
"jillz",
"jodekoeken",
"jonagold appels",
"jong belegen kaas",
"jonge kaas",
"juliennesoep",
"jupiler",
"jus",
"jus d'orange",
"juspoeder",
"kaarsen",
"kaas",
"kaasblokjes",
"kaasfondue",
"kaassaus",
"kaasschaaf",
"kaassouflés",
"kaasstengels",
"kabeljauwfilet",
"kadetten",
"kaiserbroodjes",
"kalfsfilet",
"kalfsleverworst",
"kalfsragout",
"kalkoenfilet",
"kalkreiniger",
"kampioentjes",
"kandijkoek",
"kaneel",
"kaneelijs",
"kaneelstengels",
"kaneelstokjes",
"kano's",
"kant en klaar maaltijd",
"kappertjes",
"kapucijners",
"karamelvla",
"karbonade",
"kardemom",
"karnemelk",
"karvan cevitam",
"karwijzaad",
"kastanjechampignons",
"katenspek",
"kattenbakkorrels",
"kattenbakvulling",
"kattenbrokken",
"kattenmelk",
"kattenvoer",
"kauwgom",
"keelpastilles",
"kellogg's",
"kerrie",
"kerriesaus",
"kersenjam",
"kervel",
"ketchup",
"ketjap",
"ketoembar",
"keukenpapier",
"keukenreiniger",
"keukenrol",
"kibbeling",
"kidneybonen",
"kikkererwten",
"kinderijs",
"kindertoetjes",
"king",
"kip",
"kip madras",
"kip siam",
"kip tandoori",
"kipdrumsticks",
"kipfilet",
"kipfilet blokjes",
"kipfilethaasjes",
"kipgehakt",
"kipkerrie salade",
"kipkluifjes",
"kipkruiden",
"kipnuggets",
"kippenbouillon",
"kippenpoot",
"kippenpoten",
"kippensoep",
"kippenvleugels",
"kiprollade",
"kipsate",
"kipsatesalade",
"kipschnitzel",
"kitkat",
"kiwi",
"knackebrod",
"knakworst",
"knakworsten",
"knoflook",
"knoflookboter",
"knoflookbroodjes",
"knoflookmayonaise",
"knoflookolijven",
"knoflookpoeder",
"knoflooksaus",
"knolselderij",
"knorr mix",
"knorr wereldgerecht",
"koek",
"koekjes",
"koekrepen",
"koenjitpoeder (geelwortel)",
"koffie",
"koffiebonen",
"koffiebroodje",
"koffiecreamer",
"koffiecups",
"koffiefilters",
"koffiekoekjes",
"koffiemelk",
"koffiepads",
"koffieroom",
"kofta",
"kogelbiefstuk",
"kokos",
"kokosbloemsuiker",
"kokosbloesemsuiker",
"kokosbrood",
"kokoskransen",
"kokosmeel",
"kokosmelk",
"kokosolie",
"kokosyoghurt",
"koksroom",
"komijnkaas",
"komijnzaad",
"komkommer",
"komkommerrauwkost",
"komkommersalade",
"kookroom",
"koolrabi",
"koopmans mix",
"koriander",
"kouseband",
"krab",
"krabsalade",
"krakelingen",
"krenten",
"krentenbollen",
"krentenbrood",
"krieltjes",
"krieltjes barbecue",
"kroepoek",
"kroketten",
"krop sla",
"kruiden",
"kruidenboter",
"kruidenkaas",
"kruidenmix",
"kruidenpasta",
"kruidkoek",
"kruidnagel",
"kruimige aardappelen",
"krulsla",
"kurkuma",
"kwark",
"la trappe",
"lactacyd",
"lamp",
"lampolie",
"lamsbiefstuk",
"lamsburger",
"lamskoteletten",
"lamsrack",
"lamsworstjes",
"lange vingers",
"laos",
"lasagne",
"lasagnebladen",
"lasagnesaus",
"laurierblad",
"leffe blond",
"lekkerbek",
"lentebok",
"lenteui",
"lenzenvloeistof",
"leverpastei",
"leverworst",
"libresse",
"liga",
"lijnzaad",
"likeur",
"limoenen",
"limoensap",
"limonade",
"limonadesiroop",
"linzen",
"listerine",
"loempia",
"lollies",
"lotus keukenrol",
"luchtverfrisser",
"lucifers",
"luiers",
"luierzakjes",
"luikse wafels",
"m&m's",
"maaltijdsalade",
"maaltijdwrap",
"maandverband",
"maanzaad",
"maaslander",
"macaroni",
"macaroni groente",
"macaroni/spaghetti groente",
"macaroni/spaghetti mix",
"macaronimix",
"madeira",
"magere melk",
"magere rookworst",
"magere spekreepjes",
"magere yoghurt",
"maggi aroma",
"magnetronfolie",
"magnum",
"mais",
"maisbrood",
"maiskolven",
"maizena",
"makreel",
"maltesers",
"mandarijnen",
"mango",
"mangosap",
"margarine",
"marjolein",
"marmelade",
"marsepein",
"marshmallows",
"marsrepen",
"martini",
"mascarpone",
"matzecrackers",
"mayonaise",
"mayonaise met yoghurt",
"maïskip",
"maïzena",
"medium dry sherry",
"melbatoast",
"melk",
"melkbiscuit",
"melkpoeder",
"meloen",
"mentos",
"merci",
"mergpijp",
"mergpijpjes",
"meringue",
"metworst",
"mezzelune ricotta & spinazie",
"mie",
"mierikswortel",
"mihoen",
"milk & fruit",
"milk and fruit",
"mineraalwater",
"minibolletjes",
"minneola",
"mints",
"monchou",
"mondwater",
"mortadella (vleeswaren)",
"mosselen",
"mosselgroente",
"mosselsaus",
"mosterd",
"mosterdsaus",
"mosterdsoep",
"mozzarella",
"muesli",
"muesli-notenbrood",
"mueslibroodjes",
"mueslirepen",
"muffinmix",
"muffins",
"muisjes",
"multivitamine sap",
"munt",
"naanbrood",
"nacho chips naturel",
"narcissen",
"nasi",
"nasi mix",
"nasi-bami groente",
"nasi-bami vlees",
"nasikruiden",
"natuurazijn",
"nectarines",
"nescafe",
"neusspray",
"neutral",
"nibb-it",
"nivea",
"noedels",
"noodles",
"nootjes",
"nootmuskaat",
"nori-vellen",
"noten",
"notenmix",
"notenpasta",
"notenrijst",
"nougat",
"nutella",
"nutrilon",
"oestersaus",
"oesterzwammen",
"old amsterdam-kaas",
"olie",
"olijfmayonaise",
"olijfolie",
"olijfolie extra vierge",
"olijfolie mild",
"olijfolie spray",
"olijven",
"olijven met ansjovis",
"olijven met feta",
"olijven zonder pit",
"olvarit",
"omelet mix",
"omo",
"ontbijtdrank",
"ontbijtkoek",
"ontbijtkoekrepen",
"ontbijtsmoothie",
"ontbijtspek",
"onthardingszout",
"ontstopper",
"oogmake-up remover",
"oosterse wokgroente",
"oploskoffie",
"optimel",
"oral b",
"orangina",
"oregano",
"ossehaas",
"ossenstaartsoep",
"ossenworst",
"oude kaas",
"oudewijvenkoek",
"ovenfrites",
"ovenschotel mix",
"paddestoelenmelange",
"paella",
"page toiletpapier",
"pakjes drinken",
"paksoi",
"paling",
"palingworst",
"palm bier",
"pampers",
"pancetta",
"pandanrijst",
"paneermeel",
"pangasiusfilet",
"pannenkoeken",
"pannenkoekmeel",
"pannenkoekmix",
"pap",
"pappardelle",
"paprika mix",
"paprikapoeder",
"paracetamol",
"paradontax",
"parijse worteltjes",
"parmaham",
"parmezaanse kaas",
"parmigiano",
"parodontax",
"pasta",
"pastasaus",
"pastaschelpjes",
"pastinaak",
"patat",
"pate",
"paturain",
"pecannoten",
"pecorino kaas",
"pedaalemmerzakken",
"peen",
"peen julienne",
"pekelborst",
"pekelvlees",
"penne rigate",
"peper",
"pepermunt",
"pepernoten",
"pepersaus",
"pepersteak",
"pepertjes",
"pepsi cola",
"peren",
"persil",
"perssinaasappels",
"perziken",
"pesto",
"peterselie",
"petrella met bieslook",
"peulen",
"piccalilly",
"pickwick thee",
"pijnboompitten",
"pils",
"pinda's",
"pindakaas",
"pindakoeken",
"pindarotsjes",
"pindasaus",
"pinot gris",
"pistachenoten",
"pistolet",
"pitabroodjes",
"pizza (diepvries)",
"pizza (vers)",
"pizzabodemmix",
"pizzabrood",
"pizzadeeg",
"plastic bekers",
"plastic borden",
"plastic lepels",
"plastic messen",
"plastic vorken",
"platte peterselie",
"pleisters",
"poedersuiker",
"pofaardappels",
"poffertjes",
"poffertjesmix",
"pompoen",
"pompoenpitten",
"pompoensoep",
"popcorn",
"port",
"port salut",
"prei",
"pretzels",
"pringles",
"pritt",
"prodent",
"prosecco",
"provencaalse kruidenmix",
"pruimen",
"pudding",
"puntjes",
"puntpaprika's",
"puree",
"pyjamapapje",
"quiche",
"quiche mix",
"quinoa",
"quorn",
"rabarbercompote",
"radijs",
"ragout",
"ranja",
"rauwe ham",
"rauwkost",
"ravioli",
"red bull",
"rexona",
"rib eye",
"ribbelchips",
"ribkarbonade",
"riblappen",
"ricotta",
"rietjes",
"rietsuiker",
"rijst",
"rijstazijn",
"rijstdessert",
"rijstepap",
"rijstpap",
"rijstvellen",
"rijstwafels",
"risotto",
"risottorijst",
"rivella",
"rivierkreeftjes",
"robijn",
"rode bieten",
"rode curry boemboe",
"rode grapefruit",
"rode kool",
"rode paprika",
"rode peper",
"rode pesto",
"rode uien",
"rode wijn",
"rode wijnazijn",
"roerbakgroente",
"roerbakmie",
"roerbakrijst",
"roerbaksaus",
"roggebrood",
"rollade",
"roma tomaten",
"rookkaas",
"rookvlees",
"rookworst",
"room",
"roomboter",
"roomijs",
"roomkaas",
"roompate",
"roomsaus",
"roosvicee",
"roquefort",
"rosbief",
"rosbieflapjes",
"rosé wijn",
"rosébier",
"roze garnalen",
"roze koeken",
"rozemarijn",
"rozen",
"rozenbotteljam",
"rozijnen",
"rozijnenbrood",
"rucola",
"rum",
"runderballetjes",
"runderchipolata",
"rundergehakt",
"runderlappen",
"runderlever",
"runderreepjes",
"runderrookvlees",
"runderrookworst",
"rundertartaar",
"rundervinken",
"rundvlees salade",
"rundvleesbouillon",
"rösti",
"röstirondjes",
"salade",
"salademix",
"salami",
"salie",
"salsa",
"sambal",
"sandwichspread",
"sanex",
"sap",
"sardientjes",
"satesaus",
"satestokjes",
"saté",
"saucijzenbroodje",
"sausmix",
"scharreleieren",
"scheergel",
"scheermesjes",
"scheerschuim",
"schenkel",
"schilmes",
"schnitzel",
"scholfilet",
"schoonmaakazijn",
"schoonmaakdoekjes",
"schouderham",
"schouderkarbonade",
"schrijfblok",
"schuddebuikjes",
"schuimblokken",
"schuimpjes",
"schuurmiddel",
"schuursponsjes",
"schuursponzen",
"scotch",
"selderij",
"selderijknol",
"selleriesalade",
"senseo pads",
"sensodyne",
"seroendeng",
"serranoham",
"servetten",
"sesamzaad",
"seven up",
"shag",
"shampoo",
"shampoo etos",
"shii take",
"shoarmabroodjes",
"shoarmasaus",
"shoarmavlees",
"sigaretten",
"sinaasappelen",
"sinaasappelsap",
"sinas",
"siroop",
"sisi",
"sjalotten",
"sla",
"slaburger",
"sladressing",
"slagroom",
"slagroomijs",
"slagroomsoesjes",
"slasaus",
"slavinken",
"smarties",
"smeerkaas",
"smeerkaas naturel",
"smeerleverworst",
"smeerworst",
"smint",
"smoothie",
"snert",
"snijbonen",
"snijworst",
"snoep",
"snoepgroente",
"snoeptomaatjes",
"snoetenpoetsers",
"soda",
"soep",
"soeparoma",
"soepballetjes",
"soepgroente",
"soepgroenten",
"soepmaker",
"soeppakket",
"soepstengels",
"soepvlees",
"soesjes",
"soja",
"soja yoghurt",
"sojadrink",
"sojamelk",
"sojasaus",
"sokken",
"sorbet ijs",
"sour cream",
"sourcy",
"soya",
"spa & fruit",
"spa rood",
"spaanse peper",
"spaghetti",
"spaghetti saus",
"spaghettimix",
"spaghettini",
"spareribs",
"speciaal bier",
"special k",
"speculaas",
"speculaasbrokken",
"speculoos",
"spek",
"spekblokjes",
"spekjes",
"spekken",
"spekkies",
"speklapjes",
"speklappen",
"spekreepjes",
"spelt beschuit",
"spelt crackers",
"speltbrood",
"speltmeel",
"speltpasta",
"sperziebonen",
"spianata romana",
"spinazie à la crème",
"spiritus",
"spitskool",
"spliterwten",
"spoelglans middel",
"sportdrank",
"sprite",
"spritsen",
"spruitjes",
"stamppot",
"stamppot aardappelen",
"steak",
"steak de boeuf",
"stofzuigerzakken",
"stokbrood",
"stoommaaltijden",
"strepsils",
"stroganoffsaus",
"stroop",
"stroopkoeken",
"stroopwafels",
"studentenhaver",
"sucadelappen",
"sudocreme",
"sugar snaps",
"suiker",
"suikerbrood",
"suikerklontjes",
"suikerpinda's",
"suikerstaafjes",
"suikerwafels",
"sultana",
"sun",
"surimi sticks",
"sushi",
"sushirijst",
"swiffer",
"taart",
"taartbodem",
"taartmix",
"taco mix",
"taco saus",
"taco schelpen",
"tagliatelle",
"tahoe",
"taksi",
"tampons",
"tandenborstel",
"tandenstokers",
"tandfloss",
"tandoori",
"tandpasta",
"tapenade",
"tartaar",
"tartaresaus",
"tarwebloem",
"tequila",
"teriyaki",
"thee",
"theelichtjes",
"theezakjes",
"tijdschriften",
"tijm",
"tilapiafilet",
"tiramisu",
"tissues",
"tivall balletjes",
"toast",
"toblerone",
"toetje",
"toffees",
"tofu",
"toiletblokken",
"toiletpapier",
"toiletreiniger",
"tomaten",
"tomatenblokjes",
"tomatenpuree",
"tomatensap",
"tomatensaus",
"tomatensoep",
"tompoucen",
"toni&guy shampoo",
"tonic",
"tonijn",
"tonijn in olie",
"tonijn in water",
"tonijnsalade",
"tonijnsteak",
"tortellini",
"tortelloni",
"tortilla chips",
"tortilla wraps",
"tortilla's",
"tournedos",
"trekbandzakken",
"treksluitzakken",
"trostomaten",
"tuinbonen",
"tuinkers",
"tulpen",
"tum tum",
"tutti frutti",
"tzatziki",
"uien",
"uiensoep",
"undurraga",
"vaatwas tabletten",
"vaatwasmachine reiniger",
"valess schnitzels",
"vanillestokje",
"vanillesuiker",
"vanillevla",
"vanish",
"varkensfiletlapjes",
"varkensfiletrollade",
"varkenshaas",
"varkenslappen",
"varkensreepjes",
"varkensrollade",
"vastkokende aardappelen",
"vegetarisch gehakt",
"veldsla",
"venco drop",
"venkel",
"venkelthee",
"venkelzaad",
"vermicelli",
"vers sap",
"verse pasta",
"vershoud folie",
"vershoudfolie",
"viennetta",
"vieux",
"vifit",
"vijgen",
"vis",
"visbouillon",
"visfilet",
"vissaus",
"visschnitzels",
"vissticks",
"vitalu",
"vitaminedrank",
"vla",
"vlaai",
"vlaaivulling",
"vlees",
"vlees salade",
"vleesbouillon",
"vleesjus",
"vleestomaten",
"vleeswaren",
"vlekkenverwijderaar",
"vloeibare boter",
"vloerreiniger",
"vlokken",
"vochtig toiletpapier",
"vochtig wc papier",
"volkoren beschuit",
"volle melk",
"vruchtenhagel",
"vruchtenlimonade",
"vruchtensap",
"vuilniszakken",
"wafels",
"waldkorn brood",
"walnoten",
"warsteiner",
"wasa",
"wasabi",
"wasmiddel",
"waspoeder",
"wastabletten",
"wasverzachter",
"water",
"waterijs",
"watermeloen",
"watjes",
"wattenschijfjes",
"wattenstaafjes",
"waxinelichtjes",
"wc blok",
"wc eend",
"wc papier",
"weekblad",
"wereldgerecht",
"whiskas",
"whiskysaus",
"wicky",
"wieckse witte",
"wiener melange",
"wienerschnitzels",
"wijn",
"wijnazijn",
"winegums",
"winterpeen",
"winterwortel",
"wit brood",
"witbier",
"witlof",
"witte basterdsuiker",
"witte bonen",
"witte druiven",
"witte kaas",
"witte peper",
"witte reus",
"witte saus",
"witte wijn",
"wodka",
"wokgroenten",
"wokmix",
"wokolie",
"woksaus",
"wokschotel",
"worst",
"worstenbroodjes",
"worstjes",
"wortels",
"wortelspread",
"wraps",
"wraps meergranen",
"yakitori",
"yakult",
"yogho yogho",
"yoghurt",
"yoghurtdrink",
"yoghurtijs",
"yoghurtmayonaise",
"yogonaise",
"yokidrink",
"yorkham",
"zaanlander",
"zakdoekjes",
"zalm",
"zalmsalade",
"zeep",
"zeevruchten",
"zeewiersalade",
"zeezout",
"zelfrijzend bakmeel",
"zendium",
"zilvershampoo",
"zilveruitjes",
"zilvervliesrijst",
"zoete aardappel",
"zoete aardappelen",
"zoete puntpaprika",
"zoetjes",
"zoetstof",
"zongedroogde tomaat",
"zongedroogde tomaten",
"zonnebloemolie",
"zonnebloempitten",
"zout",
"zoutjes",
"zuivel",
"zuiveldrink",
"zuivelspread",
"zult",
"zure room",
"zuurkool",
"zuurkoolspek",
"zuurtjes",
"zwangerschapstest",
"zwarte olijven",
"zwarte peper",
"zweedse gehaktballetjes",
"zwitsal"
];
